# wrangler.toml
name = "gemini-proxy-panel-9"
main = "src/index.ts"
compatibility_date = "2025-03-27"
compatibility_flags = ["nodejs_compat"]

[assets]
binding = "ASSETS"
directory = "./public"

[observability]
enabled = true

[[kv_namespaces]]
binding = "GEMINI_KEYS_KV"
id = "52200fe3bb60466d814a3d76822f5a8d"

[[kv_namespaces]]
binding = "WORKER_CONFIG_KV"
id = "52200fe3bb60466d814a3d76822f5a8d"

